[[dmsext]]
== Debug Module Security Extension (non-ISA extension)

This chapter outlines the security enhancements implemented in the Debug Module. The debug operations from external debuggers will be prohibited when the debug capability is not allowed by mdbgen[i] and `sdedbgalw`.

The affected debug operations, including:

    - Halt request
    - Reset request 
    - Keepalive request 
    - Abstract commands 

Will be addressed as follows.

=== Debug Module Security Extension Discovery 

The Debug Module Security Extension imposes security constraints and introduces non-backward-compatible changes. The presence of the Debug Module Security Extension can be determined by polling the allsecured/anysecured bits in dmstatus.

=== Halt

The hart can only be halted when it is running in privilege levels specified in <<dbgpriv>>. Otherwise, the halt request will remain pending. Consequently, the response to the external debugger request may take longer than one second, and this constraint must be eliminated.

When machine mode is not permitted (mdbgen[i] set to 0) to engage in debugging, the halt-on-reset (resethaltreq) operation must fail and raise security fault error. The debugger could check the error by polling allsecfault/anysecfault bits in dmstatus as specified in <<regdmstatus>>. 

=== Reset

The reset operations must be safeguarded against various attacks. The RISC-V Debug Specification cite:[dbgspec] defines the hartreset operations, which reset selected harts. The reset operations must be prohibited when machine mode is not allowed to be debugged. The security fault error will be raised if the operation is issued when mdbgen[i] is 0. The debugger could monitor the error by polling allsecfault/anysecfault in dmstatus. 

The ndmreset operation is a system-level reset not tied to hart privilege levels and reset the entire system (excluding the Debug Module). It can only be secured by the system. Thus, it must be de-featured. The debugger can determine support for the ndmreset operation by setting the field to 1 and subsequently verifying the returned value upon reading.

=== Keepalive

The keepalive operation serves as an optional request for the hart to remain available for debugger. It is only allowed when machine mode is permitted to debug. Otherwise, it causes a security fault error when mdbgen[i] is 0, indicated by allsecfault/anysecfault bits in dmstatus.

=== Abstract Commands 
The hart's response to abstract commands is details in <<mdbgctl>> and <<submdbgctl>>. The following subsection delineates the constrains when the Debug Module issues the abstract commands. 

==== Relaxed Permission Check `relaxedpriv`

The field `relaxedpriv` in abstractcs (at 0x16) allows for relaxed permission checks, such as bypassing PMA, PMP, MMU, etc. However, this relaxation violates security requirements, and the extension mandates that `relaxedpriv` be hardwired to 0.

==== Address Translation `aamvirtual`  

The field `aamvirtual` in command (at 0x17) determines whether physical or virtual address translation is employed. However, when mdbgen[i] is 0, the extension mandates that `aamvirtual` is hardwire to 1 and memory access addresses are processed as if initiated by the hart in <<dbgaccpriv, debug access privilege>>.

=== System Bus Access 

System Bus Access enables direct reading/writing of memory space without involving the hart. However, it must always be checked by bus initiator protection mechanisms such as IOPMP, WorldGuard, etc. If these protections are not implemented or not deployed for Debug Module, System Bus Access must not be Supported. Failed system bus access attempts result in a bus security fault error (sberror 6).

[NOTE]
In scenarios where a Debug Module lacks System Bus Access, memory access by the debugger can be achieved through the use of abstract commands. These commands provide secure means of accessing memory.

[NOTE]
Trusted entities like RoT should configure IOPMP or equivalent protection before granting debug access to machine mode. Similarly, machine mode should apply the protection before enabling submachine mode debug. 

=== Security Fault Error Reporting

A dedicated error code, security fault error (cmderr 6), is included in cmderr of abstractcs (at 0x16) to signal any breaches of security enforcement by abstract commands. Additionally, the bus security fault error (sberror 6) is introduced in sberror of sbcs (at 0x38) to denote errors related to system bus access. 

The error raised by other debug operations which could be applied to selected harts such as resethaltreq, reset and keepalive can be identified through the fields allsecfault/anysecfault in dmstatus.  The security fault errors must be detectable prior to any subsequent read of the register responsible for reporting the error. Error statuses are internally maintained for each hart, with the allsecfault/anysecfault fields indicating the error status of the currently selected harts. Any error indicated by allsecfault/anysecfault remains until updated through a successful resethaltreq, reset or keepalive operation. 

[NOTE]
While the resethaltreq, reset, and keepalive operations can potentially take a significant amount of time to complete depending on the implementation, the error status can be immediately reported via following read of allsecfault/anysecfault if the operation is prohibited. Therefore, if a read of allsecfault/anysecfault indicates no error, it suggests that the operation is allowed and either currently in progress or has been successfully executed.

=== Update of Debug Module Status (dmstatus, at 0x11)

[caption="Register {counter:rimage}: ", reftext="Register {rimage}"]
[title="The `allsecured` and `anysecured` fields in dmstatus"]
[id=dmstatus]
[wavedrom, ,svg]
....
{reg: [
  {bits:   20, name: 'defined in Debug Module'},
  {bits:   1, name: 'allsecured'},
  {bits:   1, name: 'anysecured'},
  {bits:   3, name: 'defined in Debug Module'},
  {bits:   1, name: 'allsecfault'},
  {bits:   1, name: 'anysecfault'},
  {bits:   5, name: '0'},
], config:{lanes: 3, hspace:1024}}
....

[[regdmstatus]]
.The updates in dmstatus 
[options="header"]
|================================================================================================================================================
| Field       | Description                                                                                                      | Access | Reset
| allsecured  | The field is 1 when all currently selected harts implement Zedsec extension                                      | R      | -    
| anysecured  | The field is 1 when any currently selected hart implements Zedsec extension                                      | R      | -    
| allsecfault | The field is 1 when all currently selected harts have raised security fault due to reset or keepalive operation. | R      | -    
| anysecfault | The field is 1 when any currently selected hart has raised security fault due to reset or keepalive operation.   | R      | -    
|================================================================================================================================================


