[[dmextsec]]
== Debug Module Security (non-ISA) Extension

This chapter defines the required security enhancements for the Debug Module. The debug operations listed below are modified by the extension. 

* Halt
* Reset 
* Keepalive 
* Abstract commands (Access Register, Quick Access, Access Memory)
* System bus access

If any hart in the system implements the Sdsec extension, the Debug Module must also implement the Debug Module Security Extension.

=== External Debug Security Extensions Discovery 

The ISA and non-ISA external debug security extensions impose security constraints and introduce non-backward-compatible changes. The presence of the extensions can be determined by polling the ALLSECURED and/or ANYSECURED bits in `dmstatus` <<regdmstatus>>. These bits will read as 0 when `nsecdbg` is set to 1, regardless of whether the harts implement the Sdsec extension. When `nsecdbg` is 0, ALLSECURED is set to 1 if all currently selected harts implement the Sdsec extension, and ANYSECURED is set to 1 if any currently selected hart implements the Sdsec extension. When any hart implements the Sdsec extension, it indicates that the Debug Module implements the Debug Module Security Extension as described in this chapter.

=== Halt 

The halt behavior for a hart is detailed in <<sdsecextdbg>>. According to _The RISC-V Debug Specification_ cite:[dbgspec], a halt request must be responded to within one second. However, this constraint must be removed as the request might be pending due to situations where debugging is disallowed. In the case of a halt-on-reset request (SETRESETHALTREQ), the request is only acknowledged by the hart once it has reached a privilege level in which debug is allowed. 

=== Reset

The HARTRESET operation resets selected harts. When M-mode is disallowed to be debugged, the hart will raise a security fault error to the Debug Module on HARTRESET operations. The error can be detected through ALLSECFAULT and ANYSECFAULT in `dmstatus`.

The NDMRESET operation is a system-level reset not tied to hart privilege levels and resets the entire system (excluding the Debug Module). The Debug Module Security Extension makes NDMRESET read-only 0 when <<nsecdbg, `nsecdbg`>> is 0. The debugger can determine support for the NDMRESET operation by setting the field to 1 and subsequently verifying the returned value upon reading.

=== Keepalive

The SETKEEPALIVE bit serves as an optional request for the hart to remain available for debugging. This bit only takes effect when M-mode is allowed to be debugged; otherwise, the hart behaves as if the bit is not set.

=== Abstract Commands 
The hart's response to abstract commands is detailed in <<sdsecextdbg>>. The following subsection delineates the constraints when the Debug Module issues an abstract command. 

==== Relaxed Permission Check `relaxedpriv`

The `relaxedpriv` field is hardwired to 0.

==== Address Translation AAMVIRTUAL  

The field `command`.AAMVIRTUAL determines whether the Access Memory command uses a physical or virtual address. When `mdbgen`=1, the behavior follows the original RISC-V Debug Specification cite:[dbgspec]. When `mdbgen`=0:

* If AAMVIRTUAL=0, the hart responds with a security fault error (setting `abstractcs`.CMDERR to 6).
* If AAMVIRTUAL=1, addresses are treated as virtual and are translated and protected according to the *effective debug access privilege*, as defined in <<dbgaccpriv>>.

==== Quick Access 

When M-mode debugging is disallowed (`mdbgen`=0) for a hart, any Quick Access operation will be discarded by the Debug Module, causing `abstractcs`.CMDERR to be set to 6.

[NOTE]
Quick Access abstract commands initiate a halt, execute the Program Buffer, and resume the selected hart. These halts cannot remain pending until debugging is allowed because the debugger blocks while waiting for completion. To address this, the hart would need to distinguish between Quick Access and other halt requests. Since Quick Access is an optional optimization, the Debug Module Security Extension avoids this additional hardware complexity by disallowing Quick Access when `mdbgen` is 0.

=== System Bus Access 

The System Bus Access must be checked by bus initiator protection mechanisms such as IOPMP cite:[iopmp], WorldGuard cite:[worldguard]. The bus protection unit can return an error to the Debug Module on illegal accesses; in that case, the Debug Module will set `sbcs`.SBERROR to 6 (security fault error).

[NOTE]
Trusted entities like RoT should configure IOPMP or equivalent protection before granting debug access to M-mode. Similarly, M-mode should apply the protection before enabling supervisor domain debug. 

=== Security Fault Error Reporting

A dedicated error code, security fault error (CMDERR 6), is included in `abstractcs`.CMDERR. Issuance of abstract commands under disallowed circumstances sets `abstractcs`.CMDERR to 6. Additionally, the bus security fault error (SBERROR 6) is introduced in `sbcs`.SBERROR to denote errors related to system bus access. 

Error status bits are internally maintained for each hart. The ALLSECFAULT and ANYSECFAULT fields in `dmstatus` indicate the error status of the currently selected harts. These error statuses are sticky and can only be cleared by writing 1 to `dmcs2`.ACKSECFAULT <<regdmcs2>>.

[[nsecdbg]]
=== Non-secure Debug 

The state element `nsecdbg` is introduced to retain full debugging capabilities, as if the extensions in this specification were not implemented. When `nsecdbg` is set to 1:

* All <<dbops, debug operations>> are executed with M-mode privilege (equivalent to having `mdbgen` set to 1) for all harts in the system.
* The NDMRESET operation is allowed.
* The RELAXEDPRIV field may be configurable.
* System Bus Access may bypass the bus initiator protections.
* Trace output is enabled in all privilege modes.  

=== Update of Debug Module Registers

The Debug Module Security Extension introduces new fields in the Debug Module registers. In `dmstatus`, ANYSECURED and ALLSECURED are added at bit 20 and bit 21 respectively, while ANYSECFAULT and ALLSECFAULT are added at bit 25 and bit 26. The ACKSECFAULT field is added to `dmcs2` at bit 12.

//[caption="Register {counter:rimage}: ", reftext="Register {rimage}"]
//[title="Newly introduced fields in dmstatus"]
//[id=dmstatus]
//[wavedrom, ,svg]
//....
//{reg: [
//  {bits:   20, name: 'defined in Debug Module'},
//  {bits:   1, name: 'anysecured'},
//  {bits:   1, name: 'allsecured'},
//  {bits:   3, name: 'defined in Debug Module'},
//  {bits:   1, name: 'anysecfault'},
//  {bits:   1, name: 'allsecfault'},
//  {bits:   5, name: '0'},
//], config:{lanes: 3, hspace:1024}}
//....

[[regdmstatus]]
.Details of newly introduced fields in `dmstatus` 
[cols="20%,60%,10%,10%"]
[options="header"]
|================================================================================================================================================
| Field       | Description                                                                                                       | Access | Reset
| ALLSECURED  | The field is 0 when `nsecdbg` is 1. When `nsecdbg` is 0, this field is 1 if all currently selected harts implement the Sdsec extension.         | R      | -    
| ANYSECURED  | The field is 0 when `nsecdbg` is 1. When `nsecdbg` is 0, this field is 1 if any currently selected hart implements the Sdsec extension.         | R      | -    
| ALLSECFAULT | The field is 1 when all currently selected harts have raised a security fault due to reset or keepalive operation | R      | -    
| ANYSECFAULT | The field is 1 when any currently selected hart has raised a security fault due to reset or keepalive operation   | R      | -    
|================================================================================================================================================


//[caption="Register {counter:rimage}: ", reftext="Register {rimage}"]
//[title="Newly introduced acksecfault in dmcs2"]
//[id=dmcs2]
//[wavedrom, ,svg]
//....
//{reg: [
//  {bits:   12, name: 'defined in Debug Module'},
//  {bits:   1, name: 'acksecfault'},
//  {bits:   19, name: '0'},
//], config:{lanes: 2, hspace:1024}}
//....

[[regdmcs2]]
.Detail of ACKSECFAULT in `dmcs2`
[cols="20%,60%,10%,10%"]
[options="header"]
|================================================================================================================================================
| Field       | Description                                                                                                      | Access | Reset
| ACKSECFAULT |0 (nop): No effect.

1 (ack): Clears error status bits for any selected harts. 

| W1      | -    

|================================================================================================================================================

