[[intro]]
== Introduction
Debugging and tracing are essential tools utilized by developers to identify and rectify software and hardware issues, optimize performance, and ensure robust system functionality. The debugging and tracing extensions in RISC-V ecosystem play a pivotal role in enabling these capabilities, allowing developers to monitor and control the execution of programs during the development, testing and production phases. However, the current RISC-V Debug and trace specification grants the external debugger highest privilege in the system, regardless of the privilege level at which the target system is running. It leads to privilege escalation issues when multiple actors are present. 

This specification defines non-ISA extension <<dmsext, Debug Module Security Extension (non-ISA extension)>> and ISA extension <<Sdsec, Sdsec (ISA extension)>> to address the above security issues in the current RISC-V Debug Specification cite:[dbgspec] and trace specifications cite:[etrace] cite:[ntrace]. 

Below list summarizes changes introduced by external debug specification when implemented:

    - *Per-Hart Debug Control (Smsdedbg extension cite:[smmtt]):* Separate control knobs are introduced for each hart, specifically for machine mode and supervisor domains cite:[smmtt].
    - *Debugging Restrictions:* The external debugger is restricted to halting the hart only when it is in a debug-allowed machine mode program or supervisor domain.
    - *Operations Constraints:* All debug operations, such as memory accesses and CSR accesses, are constrained by the per-hart control knobs.
    - *Memory Protection:* The external debugger cannot bypass the memory translation or protection mechanisms enforced on the hart.
    - *System Bus Access Protection:* Optional. If implemented, System Bus Access must be protected by a bus initiator protection mechanism, such as IOPMP or WorldGuard.
    - *Trigger Constraints:* The firing or matching of triggers is constrained by the per-hart control knobs.
    - *Per-Hart Trace Control Knobs (Smsdetrc extension cite:[smmtt]):* Dedicated per-hart control knobs are introduced for tracing, specifically for machine mode and supervisor domains.
    - *Trace Encoder Control:* The trace encoder is enabled or disabled by a sideband signal from the hart to the trace encoder, controlled according to the per-hart knobs.

=== Terminology

[cols="2*"]
[cols="20%,80%"]
|=====================================================================================================================================================
| Abstract command       | a high-level command in Debug Module used to interact with and control harts                                               
| Debug Access Privilege | the privilege with which abstract commands or instructions in program buffers access hardware resources                    
| Debug Mode             | an additional privilege mode to support off-chip debugging                                                                 
| Hart                   | a RISC-V hardware thread                                                                                                   
| IOPMP                  | Input-Output Physical Memory Protection unit                                                                               
| Machine mode           | the highest privileged mode in the RISC-V privilege model                                                                  
| PMA                    | Physical Memory Attributes                                                                                                 
| PMP                    | Physical Memory Protection unit                                                                                            
| Program buffer         | a buffer in Debug Module to execute arbitrary instructions on a hart                                                       
| Supervisor domain      | a isolated supervisor execution context defined in RISC-V Supervisor Domains Access Protection cite:[smmtt]                
| Trace encoder          | a piece of hardware that takes in instruction execution information from a RISC-V hart and transforms it into trace packets
|=====================================================================================================================================================
