[[intro]]
== Introduction
Debugging and tracing are essential tools utilized by developers to identify and rectify software and hardware issues, optimize performance, and ensure robust system functionality. The debugging and tracing extensions in RISC-V ecosystem play a pivotal role in enabling these capabilities, allowing developers to monitor and control the execution of programs during the development, testing and production phases. However, the current RISC-V Debug and trace specification grants the external debugger highest privilege in the system, regardless of the privilege level at which the target system is running. It leads to privilege escalation issues when multiple actors are present. 

This specification defines non-ISA extension <<dmsext, Debug Module Security Extension (non-ISA extension)>> and ISA extension <<Sdsec, Sdsec (ISA extension)>> to address the above security issues in the current RISC-V Debug Specification cite:[dbgspec] and trace specifications cite:[etrace] cite:[ntrace]. 

Below list summarizes changes introduced by external debug specification:

    - *Per-Hart Debug Control:* Introduce per-hart control nobs to control whether external debug is allowed in machine mode or supervisor domains cite:[smmtt]
    - *Debug Mode:* External debugger can only halt the hart and enter debug mode when debug is allowed in current privilege mode; All operations are executed with <<dbgaccpriv, debug privilege>> instead of machine mode privilege
    - *Memory Access:* Memory access from a hart’s point of view using a Program Buffer or the Abstract Access Memory command must be checked by the hart's memory protection mechanisms as if the hart is running at <<dbgaccpriv, debug privilege>>; Memory access from Debug Module using System Bus Access block without involving a hart must be checked by system memory protection mechanism, such as IOPMP or WorldGuard
    - *Register Access:* Register access using Program Buffer or the Abstract Access Register command works as if the hart is running in <<dbgaccpriv, debug privilege>> instead of machine mode privilege
    - *Triggers:* Triggers can only fire or match when external debug is allowed in current privilege
    - *Per-Hart Trace Control:* Introduce per-hart knobs to control whether tracing is allowed in machine mode and supervisor domains cite:[smmtt]
