[[Sdsec]]
== Sdsec (ISA extension)

This chapter introduces the Sdsec ISA extension, which adds security enhancements to the Sdext/Sdtrig cite:[dbgspec] and trace functionality cite:[etrace] cite:[ntrace]. The extension provides mandatory M-mode debug and trace control, along with optional extensions for lower privilege modes.

//FIXME: how to deal with the extension defined in smmtt?
//The Sdsec extension requires the Smsdedbg cite:[smmtt] extension to be implemented, and the Smsdetrc cite:[smmtt] extension if trace functionality is supported. 


It defines the following debug and trace controls:

* **M-mode Control (Smmdedbg)**: Mandatory control for M-mode external debug and trace
* **S-mode Control (Smsdedbg)**: Optional extension for S/HS-mode external debug and trace
* **VS-mode Control (Smvsdedbg)**: Optional extension for VS-mode external debug and trace  
* **U-mode Control (Smudedbg)**: Optional extension for U/VU-mode external debug and trace

When debug or trace is allowed for a privilege mode, it is allowed for all lower privilege modes as well.  

The following table summarizes the debug and trace control and associated CSRs:

[[dbgctlcsr]]
.Debug and Trace Control and CSRs
[options="header"]
|=====================================================================
| Extension          | Debug Control    | Trace Control    | New CSRs      | Target Modes
| Smmdedbg           | mdbgen           | mtrcen           | None          | M-mode
| Smsdedbg           | msdcfg.SDEDBGALW | msdcfg.SDETRCALW | sdcsr, sdpc   | S/HS-mode  
| Smvsdedbg          | msdcfg.VSEDBGALW | msdcfg.VSETRCALW | None          | VS-mode
| Smudedbg           | msdcfg.USEDBGALW | msdcfg.USETRCALW | udcsr, udpc   | U/VU-mode
|=====================================================================

[NOTE]
Users can choose to implement some or all of the optional extensions depending on their system requirements. These extensions work together to establish a hierarchical debug control model where external debug access can be restricted to specific privilege levels, preventing unauthorized debugging. 

The following table shows valid implementation combinations for different architectures:

[[validimplcomb]]
.Valid Implementation Combinations
[cols="25%,75%", options="header"]
|=====================================================================
| Architecture    | Valid Extension Combinations           
| M-only          | • Smmdedbg only                    
| M/U             | • Smmdedbg only +
                    • Smmdedbg + Smudedbg         
| M/S/U           | • Smmdedbg only +
                    • Smmdedbg + Smsdedbg +
                    • Smmdedbg + Smsdedbg + Smudedbg                     
| M/S/VS/VU/U     | • Smmdedbg only +
                    • Smmdedbg + Smsdedbg +
                    • Smmdedbg + Smsdedbg + Smvsdedbg +
                    • Smmdedbg + Smsdedbg + Smvsdedbg + Smudedbg                 
|=====================================================================


[[sdsecextdbg]]
=== External Debug

Chapter 3 of _The RISC-V Debug Specification_ cite:[dbgspec] outlines all mandatory and optional debug operations. The operations listed below are affected by the Sdsec extension; other operations remain unaffected. In the context of this chapter, *debug operations* refer to those listed below.

Debug operations affected by Sdsec: 
[[dbops]]
* Halting the hart to enter Debug Mode
* Executing the Program Buffer
* Serving abstract commands (Access Register, Access Memory)

[[dbgaccpriv]]
==== Debug Access Privilege

The *debug access privilege* is defined as the privilege level for state accesses via the hart, such as Abstract Commands and Program Buffer execution. With Sdext, Debug Mode operates as if it has M-mode privilege. When Sdsec is implemented, Debug Mode accesses registers and memory using the *debug access privilege*. Attempts from Debug Mode to access state that requires a privilege level above the *debug access privilege* will fail and set `abstractcs`.CMDERR to 3. The *debug access privilege* is derived as shown in <<dbgpriv>>.

[[dbgpriv]]
[options="header"]
[cols="5*"]
.External Debug Configuration and Privilege
|=====================================================================================================
| mdbgen | SDEDBGALW  | VSEDBGALW  | UEDBGALW   | Debug Access Privilege
| 1      | Don't care | Don't care | Don't care | M-mode                
| 0      | 1          | Don't care | Dont care  | S/HS-Mode             
| 0      | 0          | 1          | Don't care | VS-Mode               
| 0      | 0          | 0          | 1          | U/VU-Mode             
| 0      | 0          | 0          | 0          | None                  
|=====================================================================================================

==== Maximum Allowed Resume Privilege Mode

With Sdsec, the maximum privilege level that can be configured in PRV and V is determined in <<maxdbgpriv>>. The fields retain legal values when the PRV and V are configured with an illegal privilege level. Illegal privilege levels include unsupported levels and any level higher than the maximum allowed debug privilege. 

[[maxdbgpriv]]
[cols="5*", options="header"]
.Maximum Allowed Resume Privilege Mode
|=====================================================================================================
| mdbgen | SDEDBGALW  | VSEDBGALW  | UEDBGALW   | Maximum Debug Allowed Privilege on resume 
| 1      | Don't care | Don't care | Don't care | M-Mode                                         
| 0      | 1          | Don't care | Dont care  | S/HS-Mode                                  
| 0      | 0          | 1          | Don't care | VS-Mode
| 0      | 0          | 0          | 1          | U/VU-Mode
| 0      | 0          | 0          | 0          | None
|=====================================================================================================

==== Privilege-changing Instructions

Privilege-changing instructions (other than EBREAK) executed in the Program Buffer must either act as a NOP or raise an exception (stopping execution and setting `abstractcs`.CMDERR to 3). 

[[mdbgctl]]
==== M-mode Debug Control (Smmdedbg)

A state element in each hart, named `mdbgen`, is introduced to control the debuggability of M-mode for each hart as depicted in <<extdbg>>. When `mdbgen` is set to 1, debug is allowed for M-mode and the following rules apply:

- The <<dbgaccpriv, debug access privilege>> for the hart is M-mode. Abstract Commands, including "Quick Access", and Program Buffer execution operate with M-mode privilege.
- The <<dbops, debug operations>> are allowed when the hart executes in any privilege mode.

When `mdbgen` is set to 0 and the hart is running in M-mode, debug is disallowed for M-mode:

- The hart will not enter Debug Mode:
  * Halt requests will remain pending until debug is allowed.  
  * Triggers with ACTION=1 (enter Debug Mode) will not match or fire.
  * EBREAK cannot enter Debug Mode and always raises a breakpoint exception.
- The external trigger outputs (with ACTION=8/9) will not match or fire.

If the hart is running in a debug-allowed privilege mode when `mdbgen` is 0: 

- Single-stepping cannot stop in M-mode.
- Interrupts to M-mode cannot be disabled by setting `dcsr`.STEPIE=0. 

[NOTE]
When `mdbgen`=0 and `dcsr`.STEP=1, a single-stepped instruction in a debug-allowed prvilege mode may transfer control to M-mode trap handler. The hart will execute the handler in M-mode and re-enter Debug Mode immediately after an MRET instruction returns to the debug-allowed privilege mode (i.e., MRET with `mstatus`.MPP<3) . The hart shall not re-enter Debug Mode if the MRET instruction returns to a debug-disallowed privilege mode (i.e., MRET with `mstatus`.MPP=3, `mdbgen`=0). 

[NOTE]
The `mdbgen` may be controlled through various methods, such as a new input port to the hart, a handshake with the system Root of Trust (RoT), or other methods. The `mdbgen` state for the Root-of-Trust (RoT) itself should be managed by SoC hardware, likely dependent on lifecycle fusing. 
The implementation can choose to group several harts together and use one signal to drive their `mdbgen` state or assign each hart its own dedicated state. For example, a homogeneous computing system can use a signal to drive all `mdbgen` states to enforce a unified debug policy across all harts.

[NOTE]
This specification assumes the controlling entity ensures `mdbgen` shall never be set to 0 while the hart is in Debug Mode. 
Setting `mdbgen` to 0 while in Debug Mode could lead to undefined behavior; the hart may lose its debug privileges unexpectedly, potentially causing the debug session to fail or become insecure.

===== CSRs
The `dcsr`, `dpc`, and `dscratch0/1` are accessible in Debug Mode only if `mdbgen`=1; otherwise, the access will fail and `abstractcs`.CMDERR is set to 3 (exception). When external debug is disallowed in M-mode, the configuration in `dcsr` will be ignored as if it were 0.

[[smsdbgctl]]
==== S/HS-mode Debug Control (Smsdedbg)

The optional Smsdedbg extension introduces the `SDEDBGALW` field (bit 7) in CSR <<Sdseccsr,`msdcfg`>>. The `SDEDBGALW` field only takes effect when `mdbgen` is 0; otherwise, debug control is dominated by `mdbgen` as if `SDEDBGALW` is 0.

[NOTE]
All behavior described in this section applies only when `mdbgen` is 0. When `mdbgen` is 1, M-mode debug control overrides all lower privilege mode settings. 

When `SDEDBGALW` is set to 1, S/HS-mode debug is allowed:

- The <<dbgaccpriv, debug access privilege>> for the hart is S/HS-mode. Abstract Commands, including "Quick Access", and Program Buffer execution operate with S/HS-mode privilege.
- The <<dbops, debug operations>> are allowed when the hart executes in S/HS-mode.

When `SDEDBGALW` is set to 0 and the hart is running in S/HS-mode, debug is disallowed for S/HS-mode:

- The hart will not enter Debug Mode while running in S/HS-mode:
  * Halt requests will remain pending until debug is allowed.  
  * Triggers with ACTION=1 (enter Debug Mode) will not match or fire.
  * EBREAK cannot enter Debug Mode and always raises a breakpoint exception.
- The external trigger outputs (with ACTION=8/9) will not match or fire while in S/HS-mode.

When `SDEDBGALW` is set to 0 and the hart is running in a debug-allowed lower privilege mode, S/HS-mode restrictions include:

- Single-stepping cannot stop in S/HS-mode.
- Interrupts delegated to S/HS-mode cannot be disabled by setting `dcsr`.STEPIE=0. 

===== CSRs

The `sdcsr` and `sdpc` (see <<smodecsr>>) are accessible in Debug Mode if `SDEDBGALW`=1. When external debug is disallowed in S/HS-mode, the configuration visible in `sdcsr` will be ignored as if it were 0 if the hart is running in S/HS-mode.

[[smodecsr]]
====== `Sdcsr` and `sdpc`

When `SDEDBGALW` is 1, the `sdcsr` and `sdpc` registers provide S/HS-mode read/write access to the `dcsr` and `dpc` registers respectively. However, `sdcsr` does not expose access to the `MPRVEN` field; instead, it repurposes the `MPRVEN` bit position with a `DMPRV` field to modify the *effective debug access privilege* in S/HS-mode. Both registers are only accessible in Debug Mode.

.Allocated addresses for S/HS-mode shadow of Debug Mode CSR  
[options="header"]
[cols="25%,25%,50%"]
|============================================================================================
| Number   | Name       | Description
| 0xaaa    | sdcsr      | S/HS-mode debug control and status register.
| 0xaaa    | sdpc       | S/HS-mode debug program counter. 
|============================================================================================

The `sdcsr` register exposes a subset of `dcsr`, formatted as shown in <<sdcsr32>>, while the `sdpc` register provides full access to `dpc`.

[NOTE]
Unlike `dcsr` and `dpc`, the `dscratch0/1` registers do not have a S/HS-mode access mechanism, and external debuggers with S/HS-mode privilege cannot use them.

[caption="Register {counter:rimage}: ", reftext="Register {rimage}"]
[title="S/HS-mode debug control and status register (sdcsr)"]
[id=sdcsr32]
[wavedrom, ,svg]
....
{reg: [
  {bits:   1, name: 'PRV'},
  {bits:   1, name: '0'},
  {bits:   1, name: 'STEP'},
  {bits:   1, name: '0'},
  {bits:   1, name: 'DMPRV'},
  {bits:   1, name: 'V'},
  {bits:   3, name: 'CAUSE'},
  {bits:   1, name: '0'},
  {bits:   1, name: '0'},
  {bits:   1, name: 'STEPIE'},
  {bits:   1, name: 'EBREAKU'},
  {bits:   1, name: 'EBREAKS'},
  {bits:   1, name: '0'},
  {bits:   1, name: '0'},
  {bits:   1, name: 'EBREAKVU'},
  {bits:   1, name: 'EBREAKVS'},
  {bits:   6, name: '0'},
  {bits:   3, name: 'EXTCAUSE'},
  {bits:   1, name: '0'},
  {bits:   4, name: 'DEBUGVER'}
], config:{lanes: 3, hspace:1024}}
....

[NOTE]
The NMIP, MPRVEN, STOPTIME, STOPCOUNT, EBREAKM, and CETRIG fields in `dcsr` are configurable only by M-mode; they are masked in `sdcsr`, while PRV[1] is hardwired to 0 in `sdcsr`. The field for MPRVEN is reclaimed by DMPRV in `sdcsr` layout to avoid waste of fields. 

The DMPRV field is added as bit 4 in `sdcsr` to modify the *effective debug access privilege* for memory load and store accesses, as defined in <<effectivedbgpriv>>.

[[dmprv]]
.Details of the `dmprv` field in `sdcsr`
[options="header"]
[cols="15%,55%,15%,15%"]
|=================================================================================================================================================================
| Field | Description                                                                                                                          | Access | Reset  
| DMPRV | 0 (normal): The privilege level in Debug Mode is not modified.

1: In Debug Mode, the privilege level for load and store operations is modified and indicated by `sstatus`.SPP and `hstatus`.SPV.| WARL   | 0      
|=================================================================================================================================================================

====== Extension of Sdtrig CSR

The Smtdeleg/Sstcfg cite:[smtdeleg] extensions define the process for delegating triggers to modes with lower privilege than M-mode. If Sdtrig is supported, the Sdsec requires both extensions to securely delegate Sdtrig triggers to the S/HS-mode.

[NOTE]
When M-mode enables debugging for the S/HS-mode, it can optionally delegate the triggers to the S/HS-mode, allowing an external debugger with S/HS-mode privilege to configure these triggers.

[[effectivedbgpriv]]
===== Debug Access Privilege to memory

The `sdcsr`.DMPRV takes effect when `mdbgen` is 0, and it is read-only 0 when `mdbgen` is 1. With `SDEDBGALW` set to 1, the *effective debug access privilege* of loads and stores by an S/HS-mode debugger to access memory in Debug Mode can be modified by `sdcsr`.DMPRV. When `sdcsr`.DMPRV=0, the *effective debug access privilege* of loads and stores in Debug Mode follows <<dbgpriv>>; when `sdcsr`.DMPRV=1, the *effective debug access privilege* of loads and stores in Debug Mode is represented by:

- `sstatus`.SPP or,
- `hstatus`.SPVP and `hstatus`.SPV if hypervisor externsion is supported.

The `sdcsr`.DMPRV does not affect the virtual-machine load/store instructions, HLV, HLVX, and HSV. 

==== VS-mode Debug Control (Smvsdedbg)

The optional Smvsdedbg extension introduces the `VSEDBGALW` field (bit 8) in CSR <<Sdseccsr,`msdcfg`>>. The `VSEDBGALW` field only takes effect when both `mdbgen` and `SDEDBGALW` are 0; otherwise, debug control is dominated by `mdbgen` or `SDEDBGALW` as if `VSEDBGALW` is 0.

[NOTE]
All behavior described in this section applies only when both `mdbgen` and `VSEDBGALW` are 0. When `mdbgen` is 1 or `VSEDBGALW` is 1, M-mode debug control or S/HS-mode debug control overrides all lower privilege mode settings. 

When `VSEDBGALW` is set to 1, VS-mode debug is allowed:

- The <<dbgaccpriv, debug access privilege>> for the hart is VS-mode. Abstract Commands, including "Quick Access", and Program Buffer execution operate with VS-mode privilege.
- The <<dbops, debug operations>> are allowed when the hart executes in VS-mode.

When `VSEDBGALW` is set to 0 and the hart is running in VS-mode, debug is disallowed for VS-mode:

- The hart will not enter Debug Mode while running in VS-mode:
  * Halt requests will remain pending until debug is allowed.  
  * Triggers with ACTION=1 (enter Debug Mode) will not match or fire.
  * EBREAK cannot enter Debug Mode and always raises a breakpoint exception.
- The external trigger outputs (with ACTION=8/9) will not match or fire while in VS-mode.

When `VSEDBGALW` is set to 0 and the hart is running in a debug-allowed lower privilege mode, VS-mode restrictions include:

- Single-stepping cannot stop in VS-mode.
- Interrupts delegated to VS-mode cannot be disabled by setting `sdcsr`.STEPIE=0. 

===== CSRs

The `sdcsr` and `sdpc` are accessible in Debug Mode if `VSEDBGALW`=1. When external debug is disallowed in VS-mode, the configuration visible in `sdcsr` will be ignored as if it were 0.

When `VSEDBGALW` is 1, the `sdcsr` and `sdpc` registers provide VS-mode read/write access to the `dcsr`. Read/write access to the `sdcsr`.EBREAKS and `sdcsr`.EBREAKU fields are redirected to `dcsr`.EBREAKVS and `dcsr`.EBREAKVU, and writes to `sdcsr`.EBREAKVS and `sdcsr`.EBREAKVU are discarded while reads return 0. Similar to `sdcsr` access when `SEDDBGALW` is 1, `sdcsr`.DMPRV modifies the *effective debug access privilege* in VS-mode. 

[NOTE]
Redirected access to `dcsr`.EBREAKVS and `dcsr`.EBREAKVU unifies the configuration for both S/HS-mode and VS-mode.

===== Debug Access Privilege to memory

The `sdcsr`.DMPRV modifies the *effective debug access privilege* of loads and stores for a VS-mode debugger when `SDEDBGALW` is 0 and `VSEDBGALW` is 1.

When `sdcsr`.DMPRV=0, the *effective debug access privilege* of loads and stores in Debug Mode follows <<dbgpriv>>; when `sdcsr`.DMPRV=1, the *effective debug access privilege* of loads and stores in Debug Mode is represented by `vsstatus`.SPP with the virtualization mode being honored as 1. 
 
==== U-mode Debug Control (Smudedbg)

The optional Smudedbg extension introduces the `USEDBGALW` field (bit 9) in CSR <<Sdseccsr,`msdcfg`>>. The `USEDBGALW` field only takes effect when `mdbgen` and `SDEDBGALW` are 0 if virtualization mode is 0, or `mdbgen`, `SDEDBGALW`, and `VSEDBGALW` are 0 if virtualization mode is 1; otherwise, debug control is dominated by `mdbgen`, `SDEDBGALW`, or `VSEDBGALW` as if `USEDBGALW` is 0.

[NOTE]
All behavior described in this section applies only when `mdbgen`, `SDEDBGALW`, and `VSEDBGALW` are 0. 

When `USEDBGALW` is set to 1, U-mode or VU-mode (when virtualization mode is 1) debug is allowed:

- The <<dbgaccpriv, debug access privilege>> for the hart is U-mode or VU-mode. Abstract Commands, including "Quick Access", and Program Buffer execution operate with U-mode or VU-mode privilege.
- The <<dbops, debug operations>> are allowed when the hart executes in U-mode or VU-mode.

When `USEDBGALW` is set to 0 and the hart is running in U-mode or VU-mode (when virtualization mode is 1), debug is disallowed for all modes: 

- The hart will not enter Debug Mode 
  * Halt requests will remain pending until debug is allowed.  
  * Triggers with ACTION=1 (enter Debug Mode) will not match or fire.
  * EBREAK cannot enter Debug Mode and always raises a breakpoint exception.
- The external trigger outputs (with ACTION=8/9) will not match or fire 

===== CSRs

The `udcsr` and `udpc` (see <<umodecsr>>) are accessible in Debug Mode if `USEDBGALW`=1. When external debug is disallowed in U-mode or VS-mode (`USEDBGALW`=0), the configuration visible in `udcsr` will be ignored as if it were 0.

[[umodecsr]]
====== `Udcsr` and `udpc`

The `udcsr` and `udpc` registers provide U-mode or VU-mode read/write access to the `dcsr` and `dpc` registers respectively. Read/write access to the `udcsr`.EBREAKU field is redirected to `dcsr`.EBREAKVU when the virtualization mode is 1.  

.Allocated addresses for U-mode shadow of Debug Mode CSR  
[options="header"]
[cols="25%,25%,50%"]
|============================================================================================
| Number   | Name       | Description
| 0xaaa    | udcsr      | U-mode debug control and status register.
| 0xaaa    | udpc       | U-mode debug program counter. 
|============================================================================================

The `udcsr` register exposes a subset of `dcsr`, formatted as shown in <<udcsr32>>, while the `udpc` register provides full access to `dpc`.

[caption="Register {counter:rimage}: ", reftext="Register {rimage}"]
[title="U-mode debug control and status register (udcsr)"]
[id=udcsr32]
[wavedrom, ,svg]
....
{reg: [
  {bits:   2, name: '0'},
  {bits:   1, name: 'STEP'},
  {bits:   3, name: '0'},
  {bits:   1, name: 'V'},
  {bits:   3, name: 'CAUSE'},
  {bits:   2, name: '0'},
  {bits:   1, name: 'STEPIE'},
  {bits:   11,name: '0'},
  {bits:   3, name: 'EXTCAUSE'},
  {bits:   1, name: '0'},
  {bits:   4, name: 'DEBUGVER'}
], config:{lanes: 2, hspace:1024}}
....

=== Trace
When Sdsec is supported, trace, as a non-intrusive debug method, will be constrained based on RISC-V privilege level. 

[NOTE]
The availability of trace output is indicated through signals of the hart-trace interface (HTI) cite:[etrace]. These signals are influenced by both the `mtrcen` and  SDETRCALW. 

==== M-Mode Trace Control 
Each hart must add a new state element, `mtrcen`, which controls the availability of M-mode tracing. Setting `mtrcen` to 1 enables trace for both M-mode and the supervisor domain; setting `mtrcen` to 0 inhibits trace when the hart is running in M-mode.

[NOTE]
Similar to M-mode debug control, `mtrcen` may be controlled through various methods, such as a new input port to the hart, a handshake with the system Root of Trust (RoT), or other methods. The implementation may group several harts together and use one signal to drive their `mtrcen` state or assign each hart its own dedicated state. 

==== Supervisor Domain Trace Control 
The Smsdetrc extension introduces the SDETRCALW field (bit 8) in CSR <<Sdseccsr,`msdcfg`>> within a hart. The trace availability for a hart in the supervisor domain is determined by the SDETRCALW field and `mtrcen`. If either SDETRCALW or `mtrcen` is set to 1, trace can be allowed when the hart runs in the supervisor domain. 

When both SDETRCALW and `mtrcen` are set to 0, trace is inhibited at all privilege levels. 

=== Trigger Security and Access 

Triggers configured to enter Debug Mode can only match or fire when external debug is allowed, as outlined in <<dbgpriv>>. 

[NOTE]
Implementations must ensure that pending triggers intending to enter Debug Mode match or fire only when the effective privilege level is debug-allowed. For example, if an interrupt traps the hart to a debug-disallowed privilege mode, the trigger can only take effect either before the privilege is updated and control flow is transferred to the trap handler, or after the interrupt is completely handled and returns from the trap handler. The implementation must prevent Debug Mode from being entered in an intermediate state where privilege is changed or the PC is updated. This also applies to scenarios where a trigger is configured to enter Debug Mode before instruction execution and an interrupt occurs simultaneously.

==== M-mode Accessibility to DMODE in `tdata1`
 
When the Sdsec extension is implemented, DMODE is read/write for both M-mode and Debug Mode when `mdbgen` is 0, and remains only accessible to Debug Mode when `mdbgen` is 1.

[NOTE]
M-mode is given write access to DMODE to allow it to save/restore trigger context on behalf of a supervisor debugger. Otherwise, a trigger could serve as a side-channel to debug-disallowed supervisor domains. The trigger may raise a breakpoint exception in a supervisor domain where debugging is disallowed. This could allow the external debugger to indirectly observe the state from the debug-disallowed supervisor domain (PC, data address, etc.) and may even result in a Denial of Service (DoS). By making DMODE M-mode accessible when `mdbgen` is 0, such an attack can be mitigated by having M-mode firmware switch the trigger context at the supervisor domain boundary.

==== External Triggers

The external trigger outputs (with ACTION=8/9) will not match or fire when the effective privilege level of the hart exceeds debug-allowed privilege as specified in <<dbgpriv>>.

The external trigger inputs (`tmexttrigger`) can be driven by any input signals, e.g., the external trigger output from another hart, interrupt signals, etc. The initiators of these signals are responsible for determining whether the signal is allowed to assert. The hart will not acknowledge the input until it is in a debug-allowed state. For example, if the external trigger input of hart _i_ is connected to the external trigger output of hart _j_, the assertion of the output signal from hart _j_ is determined by its own allowed privilege level for debug. Hart _i_ will halt if `tmexttrigger`.ACTION is 1, when it is in a debug-allowed state and hart _j_ asserts the output signal.

=== CSRs

[[ssdextcsr]]
==== Extension of Debug Mode CSR

The `dcsr`, `dpc`, and `dscratch0/1` are accessible in Debug Mode only if `mdbgen`=1; otherwise, the access will fail and `abstractcs`.CMDERR is set to 3 (exception). The `sdcsr` and `sdpc` (see <<smodecsr>>) are always accessible in Debug Mode.

When external debug is disallowed at the current privilege level, the configuration in `dcsr` and `sdcsr` will be ignored as if they were 0.

===== `Sdcsr` and `sdpc` 

The `sdcsr` and `sdpc` registers provide supervisor read/write access to the `dcsr` and `dpc` registers respectively. Moreover, the `sdcsr` adds DMPRV to modify the *effective debug access privilege* in S-mode. Both registers are only accessible in Debug Mode. 

.Allocated addresses for supervisor shadow of Debug Mode CSR  
[options="header"]
[cols="25%,25%,50%"]
|============================================================================================
| Number   | Name       | Description
| 0xaaa    | sdcsr      | Supervisor debug control and status register.
| 0xaaa    | sdpc       | Supervisor debug program counter. 
|============================================================================================

The `sdcsr` register exposes a subset of `dcsr`, formatted as shown in <<sdcsr32>>, while the `sdpc` register provides full access to `dpc`.

[NOTE]
Unlike `dcsr` and `dpc`, the `dscratch0/1` registers do not have a supervisor access mechanism, and external debuggers with S-mode privilege cannot use them.

//[caption="Register {counter:rimage}: ", reftext="Register {rimage}"]
//[title="Supervisor debug control and status register (sdcsr)"]
//[id=sdcsr32]
//[wavedrom, ,svg]
//....
//{reg: [
//  {bits:   1, name: 'PRV'},
//  {bits:   1, name: '0'},
//  {bits:   1, name: 'STEP'},
//  {bits:   1, name: '0'},
//  {bits:   1, name: 'DMPRV'},
//  {bits:   1, name: 'V'},
//  {bits:   3, name: 'CAUSE'},
//  {bits:   1, name: '0'},
//  {bits:   1, name: '0'},
//  {bits:   1, name: 'STEPIE'},
//  {bits:   1, name: 'EBREAKU'},
//  {bits:   1, name: 'EBREAKS'},
//  {bits:   1, name: '0'},
//  {bits:   1, name: '0'},
//  {bits:   1, name: 'EBREAKVU'},
//  {bits:   1, name: 'EBREAKVS'},
//  {bits:   6, name: '0'},
//  {bits:   3, name: 'EXTCAUSE'},
//  {bits:   1, name: '0'},
//  {bits:   4, name: 'DEBUGVER'}
//], config:{lanes: 3, hspace:1024}}
//....

[NOTE]
The NMIP, MPRVEN, STOPTIME, STOPCOUNT, EBREAKM, and CETRIG fields in `dcsr` are configurable only by M-mode; they are masked in `sdcsr`, while PRV[1] is hardwired to 0 in `sdcsr`. The field for MPRVEN is reclaimed by DMPRV in `sdcsr` layout to avoid waste of fields. 

The DMPRV field is added as bit 4 in `sdcsr` to modify the *effective debug access privilege* for memory load and store accesses, as defined in <<dbgaccpriv>>.

.Details of the `dmprv` field in `sdcsr`
[options="header"]
[cols="15%,55%,15%,15%"]
|=================================================================================================================================================================
| Field | Description                                                                                                                          | Access | Reset  
| DMPRV | 0 (normal): The privilege level in Debug Mode is not modified.

1: In Debug Mode, the privilege level for load and store operations is modified and indicated by `sstatus`.SPP and `hstatus`.SPV.| WARL   | 0      
|=================================================================================================================================================================

//[caption="Register {counter:rimage}: ", reftext="Register {rimage}"]
//[title="Supervisor debug program counter (sdpc)"]
//[id=sdpc]
//[bytefield]
//----
//(defattrs :plain [:plain { :font-size 24}])
//(def row-height 40 )
//(def row-header-fn nil)
//(def left-margin 30)
//(def right-margin 30)
//(def boxes-per-row 32)
//(draw-column-headers {:height 24 :font-size 24 :labels (reverse ["0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "DXLEN-1" ""])})
//(draw-box "sdpc" {:span 32:text-anchor "middle" :borders {:left :border-unrelated :top :border-unrelated :bottom :border-unrelated :right :border-unrelated}})
//(draw-box "DXLEN" {:font-size 24 :span 32 :borders {}})
//----

==== Extension of Sdtrig CSR

The Smtdeleg/Sstcfg cite:[smtdeleg] extensions define the process for delegating triggers to modes with lower privilege than M-mode. If Sdtrig is supported, the Sdsec requires both extensions to securely delegate Sdtrig triggers to the supervisor domain.

[NOTE]
When M-mode enables debugging for the supervisor domain, it can optionally delegate the triggers to the supervisor domain, allowing an external debugger with S-mode privilege to configure these triggers.

[[Sdseccsr]]
==== Debug Control CSR

The CSR `msdcfg`, holding the debug and trace control for the supervisor domain (SDEDBGALW and SDETRCALW), is defined in _RISC-V Supervisor Domains Access Protection_ cite:[smmtt]. The Smsdedbg and/or Smsdetrc extensions must be implemented to support security control for debugging and/or tracing in supervisor domains.

