[[threatmodel]]
== External Debug Security Threat Model

Modern SoC development involves several different actors who may not trust each other, resulting in the need to isolate actors' assets during the development and debugging phases. The current RISC-V Debug specification cite:[dbgspec] grants external debuggers the highest privilege in the system, regardless of the privilege level at which the target system is running. This leads to privilege escalation issues when multiple actors are present. 

For example, the owner of an SoC, who needs to debug their firmware, may be able to use the external debugger to bypass PMP, (including PMP lock `pmpcfg`.L=1), MMU, and attack Boot ROM or other firmware (the SoC creator's asset).

Additionally, the RISC-V privilege architecture supports multiple software entities at different privilege levels that do not trust each other. These entities may be isolated from each other by mechanisms such as PMP/IOPMP or MMU, and may need different debug and trace policies. Since the external debugger is granted the highest privilege in the system, a malicious entity at a lower privilege level could compromise higher privilege software with the external debugger. Similarly, trace output from higher privilege execution could leak sensitive information to entities at lower privilege levels if not properly controlled.